### ISSUE TITLE
Work through security issues reported after enabling dependabot and other GH scans

### ISSUE THREAD

**Issue by tim-littlefair** [tim-littlefair/transit-emv-checker#27]

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by tim-littlefair** [comment]
One of the issues relates to a secret related to Google's Firebase service in android-app/google-services.json:

![Image](https://github.com/user-attachments/assets/217d4843-691e-4cbf-8c6f-c4c8ddafa670)

There is inconsistent advice on the web as to whether it is OK to put this class of API keys in publicly visible files.  

Google say it is OK, providing the default restrictions applied to the key when it is automatically previsioned are not loosened:
https://firebase.google.com/docs/projects/api-keys 
"Although it's not necessary to treat an API key for Firebase services as a secret, you should review and apply restrictions and limits as described in this section."

Others are less keen:
https://stackoverflow.com/questions/45508516/is-google-services-json-safe-from-hackers/45508703#45508703

For the moment I am going to stop using Firebase, the credential has already been deleted and I and will delete the file before next build.
